INSERT INTO spanish_dishes (nombre, categoria, aliases, token_principal, tokens_secundarios, tokens_exclusion, porcion_g, porcion_desc, kcal_ref, kcal_min, kcal_max, proteina_g, carbos_g, grasa_g, kcal_per_100g, proteina_per_100g, carbos_per_100g, grasa_per_100g, fuente_primaria, confianza, notas_claude, porciones_guia, referencias_visuales)
VALUES
('Tortilla española', 'Huevos y tortillas',
 '["tortilla de patatas","tortilla de patata","tortilla casera","pincho de tortilla","trozo de tortilla","tortilla con cebolla"]',
 'tortilla', '["patata","patatas"]', '["francesa","de maiz","mexicana","wrap"]',
 130, 'cuña estándar (1/4 tortilla)', 600, 530, 680, 12.4, 22.8, 36.2, 462, 9.5, 17.5, 27.8,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'La tortilla española siempre lleva aceite de oliva para freír la patata. NO confundir con tortilla francesa (solo huevo, sin patata, ~145 kcal). Con cebolla: +20 kcal. Restaurante: +15%. El aceite es el componente más variable.',
 '[{"desc":"pincho bar","g":50,"kcal":230},{"desc":"cuña pequeña","g":90,"kcal":415},{"desc":"cuña estándar","g":130,"kcal":600},{"desc":"cuña grande","g":180,"kcal":830},{"desc":"media tortilla","g":260,"kcal":1200}]',
 'Tortilla entera: 22-24cm diametro, 3cm altura, ~600g total. Una cuña = 1/4 tortilla. Si ocupa 2/3 del plato: cuña grande ~180g. Pincho en plato pequeño de bar: ~50g.'),

('Pan con tomate y aceite', 'Pan y desayunos',
 '["pan con tomate","pa amb tomaquet","tostada con tomate","pan tumaca"]',
 'tomate', '["pan","tostada","aceite"]', '[]',
 80, 'rebanada estándar con tomate y aceite', 195, 134, 268, 4.2, 22.0, 10.1, 244, 5.3, 27.5, 12.6,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'El aceite es el componente más variable — en España se echa generosamente (10-15ml). El tomate frotado apenas aporta calorías (~15 kcal). Pan de barra español estándar.',
 '[{"desc":"rebanada pequeña","g":55,"kcal":134},{"desc":"rebanada estándar","g":80,"kcal":195},{"desc":"rebanada grande","g":110,"kcal":268}]',
 'Rebanada estandar barra pan = 2cm grosor, ~50g pan. Con tomate frotado y aceite el peso total es ~80g. Tosta de bar suele ser mas grande ~100-110g.'),

('Bocadillo de jamon serrano', 'Pan y desayunos',
 '["bocadillo de jamon","bocata de jamon","bocadillo de serrano","bocata jamon"]',
 'bocadillo', '["jamon","serrano"]', '["iberico"]',
 180, 'bocadillo estándar de barra', 415, 300, 554, 22.0, 38.0, 12.5, 231, 12.2, 21.1, 6.9,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'Bocadillo español = pan de barra (no pan de molde). Cuarto de barra ≈ 110g pan + 40-60g jamón serrano. Con tomate y aceite: +50-80 kcal.',
 '[{"desc":"bocadillo pequeño","g":130,"kcal":300},{"desc":"bocadillo estándar","g":180,"kcal":415},{"desc":"bocadillo grande","g":240,"kcal":554}]',
 'Bocadillo estandar = barra 1/4 (~110g pan) + jamon. Si es de cuarto de barra normal de panaderia española = 180g total. Bocadillo de bar suele ser mas grande.'),

('Patatas bravas', 'Tapas y aperitivos',
 '["bravas","patatas con bravas","patatas con salsa brava"]',
 'bravas', '["patatas","patata"]', '[]',
 150, 'ración estándar de tapa', 285, 143, 418, 3.8, 32.0, 15.2, 190, 2.5, 21.3, 10.1,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'Patatas fritas con salsa brava (tomate picante) y a veces alioli. La fritura en aceite de oliva es el componente calórico principal. Ración de bar = cazuelita pequeña.',
 '[{"desc":"media ración","g":75,"kcal":143},{"desc":"ración estándar tapa","g":150,"kcal":285},{"desc":"ración grande","g":220,"kcal":418}]',
 'Racion estandar de tapa en cazuelita pequeña = ~150g. Si es plato compartido entre 2-3 personas multiplicar. Cazuelita de barro pequeña = ~150g.'),

('Lentejas con chorizo', 'Legumbres',
 '["lentejas","lentejas estofadas","lentejas con verduras","plato de lentejas"]',
 'lentejas', '["chorizo","verduras","estofadas"]', '[]',
 350, 'plato hondo estándar español', 480, 343, 617, 24.0, 48.0, 16.8, 137, 6.9, 13.7, 4.8,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'Porción española de legumbres = 300-400g (mucho más que "serving" americana de 180g). Siempre llevan sofrito base (aceite+cebolla+tomate = +80-100 kcal ya incluidas). Con chorizo: el chorizo aporta ~100 kcal por ración.',
 '[{"desc":"plato pequeño","g":250,"kcal":343},{"desc":"plato estándar","g":350,"kcal":480},{"desc":"plato grande","g":450,"kcal":617}]',
 'Plato hondo estandar español lleno = 350g. Si dice un plato sin especificar usar 350g. Tupper mediano = 400-450g.'),

('Gazpacho', 'Sopas y cremas',
 '["gazpacho andaluz","gazpacho casero"]',
 'gazpacho', '["andaluz"]', '[]',
 250, 'bowl/vaso estándar', 105, 76, 147, 1.5, 6.5, 7.8, 42, 0.6, 2.6, 3.1,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'Gazpacho lleva aceite de oliva (15-25ml por ración). NO es solo verdura triturada — el aceite aporta más de la mitad de las calorías. Versión casera más calórica que industrial.',
 '[{"desc":"vaso pequeño","g":180,"kcal":76},{"desc":"vaso/bowl estándar","g":250,"kcal":105},{"desc":"bowl grande","g":350,"kcal":147}]',
 'Vaso de agua estandar = 200ml. Bowl de sopa = 250-300ml. Taza de desayuno = 200ml. Brick individual = 330ml = 139 kcal.'),

('Croquetas caseras', 'Carnes',
 '["croquetas","croquetas de jamon","croqueta"]',
 'croqueta', '["jamon","caseras","casera"]', '[]',
 120, 'ración 3 croquetas', 290, 194, 435, 10.8, 18.0, 18.6, 242, 9.0, 15.0, 15.5,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'Croqueta casera = bechamel + relleno (jamón/pollo/bacalao) + rebozado + fritura. La fritura absorbe 8-12% del peso en aceite. Croqueta de bar suele ser más grande que casera.',
 '[{"desc":"1 croqueta mediana","g":40,"kcal":97},{"desc":"2 croquetas","g":80,"kcal":194},{"desc":"ración 3 croquetas","g":120,"kcal":290},{"desc":"ración bar 4-5 croquetas","g":180,"kcal":435}]',
 'Croqueta casera media = tamaño de un huevo pequeño, ~40g. Croqueta de bar suele ser mas grande ~50-60g. Racion estandar en bar = 4-5 uds.'),

('Paella valenciana', 'Arroces',
 '["paella","paella de pollo","paella mixta","arroz paella"]',
 'paella', '["arroz","valenciana","pollo","mariscos"]', '[]',
 350, 'ración estándar', 520, 373, 671, 22.0, 58.0, 18.2, 149, 6.3, 16.6, 5.2,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'Paella lleva sofrito + aceite abundante. El arroz absorbe caldo con grasa. Ración española es generosa (300-400g). Paella de mariscos: -50 kcal vs valenciana (menos grasa). Paella mixta: similar a valenciana.',
 '[{"desc":"ración pequeña","g":250,"kcal":373},{"desc":"ración estándar","g":350,"kcal":522},{"desc":"ración grande","g":450,"kcal":671}]',
 'Paellera de 4 personas = ~1.4kg total = 350g por persona. Si es plato de restaurante individual = 300-400g. Paella casera sirve mas.'),

('Gambas al ajillo', 'Pescados y mariscos',
 '["gambas ajillo","gambas al ajillo","langostinos al ajillo"]',
 'gambas', '["ajillo","ajo"]', '[]',
 200, 'cazuelita estándar', 280, 168, 448, 22.0, 2.0, 20.0, 140, 11.0, 1.0, 10.0,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'El aceite de oliva es el componente principal de calorías — la cazuelita lleva 30-50ml de aceite. Las gambas en sí son muy bajas en calorías (~80 kcal/100g). NO subestimar el aceite del fondo.',
 '[{"desc":"tapa pequeña","g":120,"kcal":168},{"desc":"cazuelita estándar","g":200,"kcal":280},{"desc":"plato principal","g":320,"kcal":448}]',
 'Cazuelita de barro pequeña = ~150-200g. Si es plato principal con pan = 300g+. El aceite en el fondo de la cazuela = ~30ml ya incluido en los calculos.'),

('Salmorejo', 'Sopas y cremas',
 '["salmorejo cordobes","salmorejo casero"]',
 'salmorejo', '["cordobes"]', '[]',
 200, 'bowl estándar', 196, 147, 274, 4.0, 14.0, 13.0, 98, 2.0, 7.0, 6.5,
 'BEDCA + cálculo desde ingredientes', 'alta',
 'Más denso y calórico que el gazpacho — lleva más pan y aceite. NO confundir con gazpacho (gazpacho es más líquido, ~42 kcal/100g vs salmorejo ~98 kcal/100g). Con toppings (jamón + huevo duro): +60-80 kcal.',
 '[{"desc":"vaso pequeño","g":150,"kcal":147},{"desc":"bowl estándar","g":200,"kcal":196},{"desc":"bowl grande","g":280,"kcal":274}]',
 'Bowl de sopa = 200-250ml. En restaurante suele servirse en cuenco pequeno ~150-200ml. Es mas denso que el gazpacho — mismo volumen pesa mas.');
